name: New social media post
description: Create a brief for a new social media post
title: "[SOCIAL MEDIA POST]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating this brief for a new Marketing Team task.
  - type: markdown
    attributes:
      value: |
        Before filing a new task, **please do a quick search** to check that it hasn't already been filed on the issue tracker. You can do this by checking the list of open posts [here](https://github.com/orgs/oppia/projects/40).
  - type: input
    attributes:
      label: Title of the post
      description: The title of the post that you want to make. **Example:** "Interview with current GSOC Interns"
    validations:
      required: true
  - type: input
    attributes:
      label: Subject
      description: Please provide a clear subject for the post. **Example:** "Highlighting the GSOC interns that contributed to Oppia this year."
    validations:
      required: true
  - type: input
    attributes:
      label: Goals
      description: Using any of our 3 goals, please let us know what goal Oppia is trying to achieve with this post. **Example:** "Provide great CSAT"
    validations:
      required: true
  - type: input
    attributes:
      label: Success Metrics
      description: Please choose the success metric for this post. It should tally with the goal (e.g. Goal 1 tallies with Metric 1).  **Example:** "Engagement, Action"
    validations:
      required: true
  - type: input
    attributes:
      label: Emotion
      description: Please provide the emotions you intend to evoke in our audience with this post. **Example:** "Curiosity, Awe/Inspiration, Excitement"
    validations:
      required: true
  - type: input
    attributes:
      label: What Motivates Sharing with Others
      description: What is the *hook* that would inspire our audience to share this post?
    validations:
      required: true
  - type: input
    attributes:
      label: Keywords
      description: Please provide keywords for this post. **Example:** GSOC 2023, Google Summer of Code, Internships, Tech Internships, Oppia, Opensource
    validations:
      required: true
  - type: input
    attributes:
      label: Hashtags
      description: Please provide the hashtags for this post.
    validations:
      required: true
  - type: input
    attributes:
      label: Influencers (if any)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Call to Action
      description: |
        What is the CTA for this post?
        
        **Example:** "Volunteering is also a great way to develop your skill set just like ____ has done. Click to Volunteer. OR Contributing is a great way to improve your tech skills and contribute to opensource projects. Contribute to Oppia today."
    validations:
      required: true
