name: New social media post
description: Create a brief for a new social media post
title: "[SOCIAL MEDIA POST]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating this brief for a new Marketing Team task.
  - type: markdown
    attributes:
      value: |
        Before filing a new task, **please do a quick search** to check that it hasn't already been filed on the issue tracker. You can do this by checking the list of open posts [here](https://github.com/orgs/oppia/projects/40).
  - type: input
    attributes:
      label: Topic of the post
      description: The topic of the post that you want to make. **Example:** "Interview with current GSOC Interns"
    validations:
      required: true
  - type: input
    attributes:
      label: Goals
      description: Using any of our 3 goals, please let us know what goal Oppia is trying to achieve with this post. **Example:** "Provide great CSAT"
    validations:
      required: true
  - type: input
    attributes:
      label: Success Metrics
      description: Please choose the success metric for this post. It should tally with the goal (e.g. Goal 1 tallies with Metric 1).  **Example:** "Engagement, Action"
      multiple: false
      options:
        - Followers
        - Likes
        - Shares
        - Impressions
        - Clicks
    validations:
      required: true
  - type: input
    attributes:
      label: Emotion
      description: Please provide the emotions you intend to evoke in our audience with this post. **Example:** "Curiosity, Awe/Inspiration, Excitement"
    validations:
      required: true
  - type: textarea
    attributes:
      label: What Motivates Sharing with Others
      description: |
        What is the *hook* that would inspire our audience to share this post? 
        
        **Example:** being seen as working for a worthy cause.
    validations:
      required: true
  - type: input
    attributes:
      label: Hashtags (for social media)
      description: Any relevant terms being used that releate to the post and are often commonly used, e.g. `#education`.
    validations:
      required: true
  - type: input
    attributes:
      label: Influencers (if any)
      description: List social media handles of any relevant influencers here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Call to Action
      description: |
        What is the CTA for this post?
        
        **Example:** "Click to Volunteer" OR "Contribute to Oppia today."
    validations:
      required: true
